# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Common configuration used by both pipelines

variables:
- name: poolName
  value: 'StlBuild-2024-02-13T1246-Pool'
  readonly: true
- name: poolDemands
  value: 'EnableSpotVM -equals true'
  readonly: true
- name: tmpDir
  value: 'D:\Temp'
  readonly: true
- name: buildOutputLocation
  value: 'D:\build'
  readonly: true
- name: benchmarkBuildOutputLocation
  value: 'D:\benchmark'
  readonly: true
- name: Codeql.SkipTaskAutoInjection
  value: true
  readonly: true
