# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Common configuration used by both pipelines

variables:
- name: poolName
  value: 'Stl-2026-01-13T1248-x64-Pool'
  readonly: true
- name: arm64PoolName
  value: 'Stl-2026-01-13T1248-arm64-Pool'
  readonly: true
- name: poolDemands
  value: 'EnableSpotVM -equals false'
  readonly: true
- name: launchVsDevShell
  value: 'C:\Program Files\Microsoft Visual Studio\18\Insiders\Common7\Tools\Launch-VsDevShell.ps1'
  readonly: true
- name: tmpDir
  value: 'C:\stlTemp'
  readonly: true
- name: buildOutputLocation
  value: 'C:\stlBuild'
  readonly: true
- name: benchmarkBuildOutputLocation
  value: 'C:\stlBenchmark'
  readonly: true
- name: validationBuildOutputLocation
  value: 'C:\stlValidation'
  readonly: true
- name: Codeql.SkipTaskAutoInjection
  value: true
  readonly: true
- name: skipComponentGovernanceDetection
  value: true
  readonly: true
