# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Compile TypeScript
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ">=25.1.0"
      - name: Install Packages
        run: |
          npm ci
      - name: Compile gather_stats.mts
        run: |
          npx tsc --noEmit -p src_gather/tsconfig.json
      - name: Compile status_chart.mts
        run: |
          npx tsc -p src/tsconfig.json
